repos:
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.1
    hooks:
      - id: mypy
#  - repo: https://github.com/psf/black
#    rev: 21.9b0
#    hooks:
#      - id: black
#        language_version: python3.11
