apiVersion: v1
kind: Service
metadata:
  name: hello-world-python-flask-service
  namespace: hello-world-python-flask
spec:
  type: ClusterIP
  selector:
    app: hello-world-python-flask
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
